version: "3.11"

services:
  app:
    container_name: todo_list
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    env_file:
      - .env
    ports:
      - ${FAST_API_PORT}:${FAST_API_PORT}
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15.2
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'db_data:/var/lib/postgresql/data'


volumes:
  db_data:

