"""Added new fields to Task model

Revision ID: b1c690631669
Revises: 37aca904f2e1
Create Date: 2024-01-11 12:18:18.129580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c690631669'
down_revision: Union[str, None] = '37aca904f2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('tasks', sa.Column('attachments', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attachments')
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###
